name: Weekly cross-browser testing

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 1 * * 6'

jobs:
  build-and-e2e-test-cross-browser:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [12.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          yarn install --force --non-interactive
      - name: Build Website
        run: yarn build
      - name: Run E2E Tests - Firefox
        uses: cypress-io/github-action@v1
        with:
          browser: firefox
          headless: true
          start: yarn serve --port 8000
          wait-on: 'http://localhost:8000'
          config: defaultCommandTimeout=100000,pageLoadTimeout=100000,watchForFileChanges=false,video=false
      - name: Run E2E Tests - Edge
        uses: cypress-io/github-action@v1
        with:
          browser: edge
          headless: true
          start: yarn serve --port 8000
          wait-on: 'http://localhost:8000'
          config: defaultCommandTimeout=100000,pageLoadTimeout=100000,watchForFileChanges=false,video=false
